import './globals.css';

import { Header } from '@components/Header/DesktopNav';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import FlowbiteWrapper from '@/components/FlowbiteWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <FlowbiteWrapper>
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </FlowbiteWrapper>
    </html>
  );
}
