import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import { ReactNode } from 'react';

import FlowbiteWrapper from '@/components/FlowbiteWrapper';
import Navbar from '@/components/Navbar';
import { SidebarProvider } from '@/providers/SidebarContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const cookieStore = cookies();
  const theme = cookieStore.get('theme')?.value;
  return (
    <html lang="en" className={theme}>
      <FlowbiteWrapper>
        <SidebarProvider>
          <body className={inter.className}>
            <Navbar />
            <main className="pt-16">{children}</main>
          </body>
        </SidebarProvider>
      </FlowbiteWrapper>
    </html>
  );
}
