import './globals.css';

import { Header } from '@components/Header/DesktopNav';
import { Flowbite, useThemeMode } from 'flowbite-react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode, useEffect } from 'react';

import theme from '@/flowbite-theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const dark = localStorage.getItem('theme') === 'dark';
  const [themeMode] = useThemeMode();

  useEffect(() => {
    localStorage.setItem('theme', themeMode);
  }, [themeMode]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Flowbite theme={{ dark, theme }}>
          <Header />
          {children}
        </Flowbite>
      </body>
    </html>
  );
}
