interface TagsDictionary {
  [key: string]: string;
}
// This is for outputting the tags in the correct format for the displayed label
const tagsDictionary: TagsDictionary = {
  javascript: 'JavaScript',
  python: 'Python',
  java: 'Java',
  csharp: 'C#',
  php: 'PHP',
  ruby: 'Ruby',
  typescript: 'TypeScript',
  swift: 'Swift',
  kotlin: 'Kotlin',
  cplusplus: 'C++',
  go: 'Go',
  rust: 'Rust',
  reactnative: 'React Native',
  flutter: 'Flutter',
  xamarin: 'Xamarin',
  ionic: 'Ionic',
  cordova: 'Cordova',
  r: 'R',
  perl: 'Perl',
  scala: 'Scala',
  clojure: 'Clojure',
  elixir: 'Elixir',
  elm: 'Elm',
  react: 'React',
  nodejs: 'Node.js',
  nextjs: 'Next.js',
  angular: 'Angular',
  gatsby: 'Gatsby',
  bootstrap: 'Bootstrap',
  tailwind: 'Tailwind',
  fastapi: 'FastAPI',
  graphql: 'GraphQL',
  vuejs: 'Vue.js',
  emberjs: 'Ember.js',
  backbonejs: 'Backbone.js',
  svelte: 'Svelte',
  remix: 'Remix',
  django: 'Django',
  flask: 'Flask',
  rubyonrails: 'Ruby on Rails',
  laravel: 'Laravel',
  springboot: 'Spring Boot',
  expressjs: 'Express.js',
  tensorflow: 'TensorFlow',
  apachespark: 'Apache Spark',
  pandas: 'Pandas',
  numpy: 'NumPy',
  jupyter: 'Jupyter',
  pytorch: 'PyTorch',
  keras: 'Keras',
  mysql: 'MySQL',
  postgresql: 'PostgreSQL',
  mongodb: 'MongoDB',
  sqlite: 'SQLite',
  firebase: 'Firebase',
  oracle: 'Oracle',
  microsoftsqlserver: 'Microsoft SQL Server',
  cassandra: 'Cassandra',
  redis: 'Redis',
  neo4j: 'Neo4j',
  couchdb: 'CouchDB',
  elasticsearch: 'ElasticSearch',
  solidity: 'Solidity',
  ethereum: 'Ethereum',
  hyperledger: 'Hyperledger',
  chainlink: 'Chainlink',
  truffle: 'Truffle',
  binancesmartchain: 'Binance Smart Chain',
  cardano: 'Cardano',
  polkadot: 'Polkadot',
  xrp: 'XRP',
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  expert: 'Expert',
  'short-term': 'Short-Term',
  'mid-term': 'Mid-Term',
  'long-term': 'Long-Term',
  'personal-project': 'Personal Project',
  startup: 'Startup',
  app: 'App',
  website: 'Website',
  platform: 'Platform',
  saas: 'SAAS',
  ai: 'AI',
  tool: 'Tool',
  'social-media': 'Social Media',
  'e-commerce': 'E-Commerce',
  education: 'Education',
  'info-product': 'Info-Product',
  automation: 'Automation',
  api: 'API',
  'content-creator': 'Content Creator',
  gaming: 'Gaming',
  'vr-ar': 'VR / AR',
  web3: 'Web3',
  '3d': '3D',
};

export const tags = [
  {
    category: 'Technology',
    subCategories: [
      [
        'Programming Languages',
        [
          'javascript',
          'python',
          'java',
          'csharp',
          'php',
          'ruby',
          'typescript',
          'swift',
          'kotlin',
          'cplusplus',
          'go',
          'rust',
          'reactnative',
          'flutter',
          'xamarin',
          'ionic',
          'cordova',
          'r',
          'perl',
          'scala',
          'clojure',
          'elixir',
          'elm',
        ],
      ],
      [
        'Frameworks & Libraries',
        [
          'react',
          'nodejs',
          'nextjs',
          'angular',
          'gatsby',
          'bootstrap',
          'tailwind',
          'fastapi',
          'graphql',
          'vuejs',
          'emberjs',
          'backbonejs',
          'svelte',
          'remix',
          'django',
          'flask',
          'rubyonrails',
          'laravel',
          'springboot',
          'expressjs',
          'tensorflow',
          'apachespark',
          'pandas',
          'numpy',
          'jupyter',
          'pytorch',
          'keras',
        ],
      ],
      [
        'Databases',
        [
          'mysql',
          'postgresql',
          'mongodb',
          'sqlite',
          'firebase',
          'oracle',
          'microsoftsqlserver',
          'cassandra',
          'redis',
          'neo4j',
          'couchdb',
          'elasticsearch',
        ],
      ],
      [
        'Blockchain',
        [
          'solidity',
          'ethereum',
          'hyperledger',
          'chainlink',
          'truffle',
          'binancesmartchain',
          'cardano',
          'polkadot',
          'xrp',
        ],
      ],
    ],
  },
  {
    category: 'Skill Level',
    tags: ['beginner', 'intermediate', 'expert'],
  },
  {
    category: 'Project Duration',
    tags: ['short-term', 'mid-term', 'long-term'],
  },
  {
    category: 'Project Scope',
    tags: ['personal-project', 'startup'],
  },
  {
    category: 'Domain',
    tags: [
      'app',
      'website',
      'platform',
      'saas',
      'ai',
      'tool',
      'social-media',
      'e-commerce',
      'education',
      'info-product',
      'automation',
      'api',
      'content-creator',
      'gaming',
      'vr-ar',
      'web3',
      '3d',
    ],
  },
];

export function getTagLabel(tag: string) {
  return tagsDictionary[tag];
}
